version: '3.3'

services:
    backup:
        build:
            context: .
            dockerfile: Dockerfile 
        volumes:
            - "./_data:/_data"
            - "./_backups:/_backups:rw"
    
  
